//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerafApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HerafApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حول التطبيق.
        /// </summary>
        internal static string aboutApp {
            get {
                return ResourceManager.GetString("aboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوافق.
        /// </summary>
        internal static string agreeButton {
            get {
                return ResourceManager.GetString("agreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوافق على سياسة و شروط التطبيق .
        /// </summary>
        internal static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة و شروط استخدام التطبيق.
        /// </summary>
        internal static string agreementPopup {
            get {
                return ResourceManager.GetString("agreementPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة التطبيق.
        /// </summary>
        internal static string appPolicy {
            get {
                return ResourceManager.GetString("appPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التطبيق.
        /// </summary>
        internal static string appTerms {
            get {
                return ResourceManager.GetString("appTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثالثاً: بيانات الحساب البنكي.
        /// </summary>
        internal static string bankCard {
            get {
                return ResourceManager.GetString("bankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك.
        /// </summary>
        internal static string bankName {
            get {
                return ResourceManager.GetString("bankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل كلمة المرور الجديدة و تأكيدها.
        /// </summary>
        internal static string changePasswordMessage {
            get {
                return ResourceManager.GetString("changePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        internal static string changePasswordPage {
            get {
                return ResourceManager.GetString("changePasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المدينة.
        /// </summary>
        internal static string cityPicker {
            get {
                return ResourceManager.GetString("cityPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        internal static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتَّصل بنا.
        /// </summary>
        internal static string contactApp {
            get {
                return ResourceManager.GetString("contactApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب عميل.
        /// </summary>
        internal static string customerSignupPage {
            get {
                return ResourceManager.GetString("customerSignupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا أوافق.
        /// </summary>
        internal static string donotAgreeButton {
            get {
                return ResourceManager.GetString("donotAgreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء.
        /// </summary>
        internal static string expiryDate {
            get {
                return ResourceManager.GetString("expiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور؟.
        /// </summary>
        internal static string forgetPassword {
            get {
                return ResourceManager.GetString("forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل رقم الجوال لتغيير كلمة المرور.
        /// </summary>
        internal static string forgetPasswordMessage {
            get {
                return ResourceManager.GetString("forgetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        internal static string forgetPasswordPage {
            get {
                return ResourceManager.GetString("forgetPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زائر.
        /// </summary>
        internal static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحِرفيين.
        /// </summary>
        internal static string handicraft {
            get {
                return ResourceManager.GetString("handicraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب حِرفي.
        /// </summary>
        internal static string handicraftSignupPage {
            get {
                return ResourceManager.GetString("handicraftSignupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الآيبان.
        /// </summary>
        internal static string iban {
            get {
                return ResourceManager.GetString("iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط حساب الانستقرام .
        /// </summary>
        internal static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل رقم الجوال و كلمة المرور للمتابعة.
        /// </summary>
        internal static string loginMessage {
            get {
                return ResourceManager.GetString("loginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string loginPage {
            get {
                return ResourceManager.GetString("loginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (إجباري).
        /// </summary>
        internal static string mandatory {
            get {
                return ResourceManager.GetString("mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر انتهاء البطاقة.
        /// </summary>
        internal static string monthPicker {
            get {
                return ResourceManager.GetString("monthPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (غير إجباري).
        /// </summary>
        internal static string notMandatory {
            get {
                return ResourceManager.GetString("notMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string passwordEntry {
            get {
                return ResourceManager.GetString("passwordEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        internal static string phoneEntry {
            get {
                return ResourceManager.GetString("phoneEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة إرسال رمز التحقق.
        /// </summary>
        internal static string reSendRestPassword {
            get {
                return ResourceManager.GetString("reSendRestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رمز التحقق.
        /// </summary>
        internal static string sendRestPassword {
            get {
                return ResourceManager.GetString("sendRestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب جديد .
        /// </summary>
        internal static string signupButton {
            get {
                return ResourceManager.GetString("signupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أولاً: المعلومات الشخصية.
        /// </summary>
        internal static string userInfo {
            get {
                return ResourceManager.GetString("userInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانياً: بيانات بطاقة الفيزا.
        /// </summary>
        internal static string visaCard {
            get {
                return ResourceManager.GetString("visaCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البطاقة.
        /// </summary>
        internal static string visaCardNumber {
            get {
                return ResourceManager.GetString("visaCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم صاحب البطاقة.
        /// </summary>
        internal static string visaUserName {
            get {
                return ResourceManager.GetString("visaUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .. مرحباً بك ...
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة انتهاء البطاقة.
        /// </summary>
        internal static string yearPicker {
            get {
                return ResourceManager.GetString("yearPicker", resourceCulture);
            }
        }
    }
}
